using "general" daemon for main editing

diff --git a/directories/bin/emacs-same-frame b/directories/bin/emacs-same-frame
--- a/directories/bin/emacs-same-frame
+++ b/directories/bin/emacs-same-frame
@@ -1,14 +1,14 @@
 #!/usr/bin/env bash
 #Maintained in linux-config.org
-if ! pidof "emacs"; then
-    #emacs --daemon
-    emacsclient -n -c -a "" "$@"
+emacsclient -s "general" -e "(if (> (length (frame-list)) 1) 't)" | grep -q t
+if [ "$?" = 0 ]; then
+    # echo "emacs frame found"
+    emacsclient -s "general" -n  "$@" &
 else
-    emacsclient -e "(if (> (length (frame-list)) 1) 't)" | grep -q t
-    if [ "$?" = 1 ]; then
-        emacsclient -n -c -a "" "$@"
-    else
-        emacsclient -n -a "" "$@"
-        sway-do-tool "Emacs"
-    fi
+    # echo "emacs frame NOT found"
+    exists=$(pidof "emacs")
+    echo "PID$exists"
+    emacsclient -s "general" -c "$@" &
+    [ -z "$exists" ] && sleep 5 || sleep 0.5
 fi
+sway-do-tool "Emacs"
